pkgname: mocks
filename: '{{.InterfaceName}}.go'
template: testify
template-data:
  unroll-variadic: true
packages:
  go.lumeweb.com/s3-server/internal/backend:
    config:
      dir: ./internal/backend/mocks
    interfaces:
      Backend: {}
      Factory: {}
      S3DStore: {}
  go.lumeweb.com/s3-server/internal/handlers:
    config:
      dir: ./internal/handlers/mocks
    interfaces:
      BackendRestarter: {}
      S3Swapper: {}
      SSEBroker: {}
      UpdaterManager: {}
  go.lumeweb.com/s3-server/internal/onboarding:
    config:
      dir: ./internal/onboarding/mocks
    interfaces:
      BackendInitializer: {}
  go.lumeweb.com/s3-server/internal/store:
    config:
      dir: ./internal/store/mocks
    interfaces:
      SessionManager: {}
      Store: {}
  go.lumeweb.com/s3-server/internal/version:
    config:
      dir: ./internal/version/mocks
    interfaces:
      Checker: {}
