// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/SiaFoundation/s3d/s3"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/s3-server/internal/backend"
)

// NewMockBackend creates a new instance of MockBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackend {
	mock := &MockBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBackend is an autogenerated mock type for the Backend type
type MockBackend struct {
	mock.Mock
}

type MockBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackend) EXPECT() *MockBackend_Expecter {
	return &MockBackend_Expecter{mock: &_m.Mock}
}

// BackupSQLite3 provides a mock function for the type MockBackend
func (_mock *MockBackend) BackupSQLite3(ctx context.Context, destPath string) error {
	ret := _mock.Called(ctx, destPath)

	if len(ret) == 0 {
		panic("no return value specified for BackupSQLite3")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, destPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_BackupSQLite3_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BackupSQLite3'
type MockBackend_BackupSQLite3_Call struct {
	*mock.Call
}

// BackupSQLite3 is a helper method to define mock.On call
//   - ctx context.Context
//   - destPath string
func (_e *MockBackend_Expecter) BackupSQLite3(ctx interface{}, destPath interface{}) *MockBackend_BackupSQLite3_Call {
	return &MockBackend_BackupSQLite3_Call{Call: _e.mock.On("BackupSQLite3", ctx, destPath)}
}

func (_c *MockBackend_BackupSQLite3_Call) Run(run func(ctx context.Context, destPath string)) *MockBackend_BackupSQLite3_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_BackupSQLite3_Call) Return(err error) *MockBackend_BackupSQLite3_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_BackupSQLite3_Call) RunAndReturn(run func(ctx context.Context, destPath string) error) *MockBackend_BackupSQLite3_Call {
	_c.Call.Return(run)
	return _c
}

// BucketCountForUser provides a mock function for the type MockBackend
func (_mock *MockBackend) BucketCountForUser(ctx context.Context, userName string) (int, error) {
	ret := _mock.Called(ctx, userName)

	if len(ret) == 0 {
		panic("no return value specified for BucketCountForUser")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, userName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, userName)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_BucketCountForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BucketCountForUser'
type MockBackend_BucketCountForUser_Call struct {
	*mock.Call
}

// BucketCountForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userName string
func (_e *MockBackend_Expecter) BucketCountForUser(ctx interface{}, userName interface{}) *MockBackend_BucketCountForUser_Call {
	return &MockBackend_BucketCountForUser_Call{Call: _e.mock.On("BucketCountForUser", ctx, userName)}
}

func (_c *MockBackend_BucketCountForUser_Call) Run(run func(ctx context.Context, userName string)) *MockBackend_BucketCountForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_BucketCountForUser_Call) Return(n int, err error) *MockBackend_BucketCountForUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockBackend_BucketCountForUser_Call) RunAndReturn(run func(ctx context.Context, userName string) (int, error)) *MockBackend_BucketCountForUser_Call {
	_c.Call.Return(run)
	return _c
}

// BucketOwner provides a mock function for the type MockBackend
func (_mock *MockBackend) BucketOwner(ctx context.Context, bucketName string) (string, error) {
	ret := _mock.Called(ctx, bucketName)

	if len(ret) == 0 {
		panic("no return value specified for BucketOwner")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, bucketName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, bucketName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, bucketName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_BucketOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BucketOwner'
type MockBackend_BucketOwner_Call struct {
	*mock.Call
}

// BucketOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketName string
func (_e *MockBackend_Expecter) BucketOwner(ctx interface{}, bucketName interface{}) *MockBackend_BucketOwner_Call {
	return &MockBackend_BucketOwner_Call{Call: _e.mock.On("BucketOwner", ctx, bucketName)}
}

func (_c *MockBackend_BucketOwner_Call) Run(run func(ctx context.Context, bucketName string)) *MockBackend_BucketOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_BucketOwner_Call) Return(owner string, err error) *MockBackend_BucketOwner_Call {
	_c.Call.Return(owner, err)
	return _c
}

func (_c *MockBackend_BucketOwner_Call) RunAndReturn(run func(ctx context.Context, bucketName string) (string, error)) *MockBackend_BucketOwner_Call {
	_c.Call.Return(run)
	return _c
}

// BucketStats provides a mock function for the type MockBackend
func (_mock *MockBackend) BucketStats(ctx context.Context, bucketName string) (int, int64, error) {
	ret := _mock.Called(ctx, bucketName)

	if len(ret) == 0 {
		panic("no return value specified for BucketStats")
	}

	var r0 int
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, int64, error)); ok {
		return returnFunc(ctx, bucketName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, bucketName)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) int64); ok {
		r1 = returnFunc(ctx, bucketName)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, bucketName)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBackend_BucketStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BucketStats'
type MockBackend_BucketStats_Call struct {
	*mock.Call
}

// BucketStats is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketName string
func (_e *MockBackend_Expecter) BucketStats(ctx interface{}, bucketName interface{}) *MockBackend_BucketStats_Call {
	return &MockBackend_BucketStats_Call{Call: _e.mock.On("BucketStats", ctx, bucketName)}
}

func (_c *MockBackend_BucketStats_Call) Run(run func(ctx context.Context, bucketName string)) *MockBackend_BucketStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_BucketStats_Call) Return(count int, size int64, err error) *MockBackend_BucketStats_Call {
	_c.Call.Return(count, size, err)
	return _c
}

func (_c *MockBackend_BucketStats_Call) RunAndReturn(run func(ctx context.Context, bucketName string) (int, int64, error)) *MockBackend_BucketStats_Call {
	_c.Call.Return(run)
	return _c
}

// BucketVersioning provides a mock function for the type MockBackend
func (_mock *MockBackend) BucketVersioning(ctx context.Context, bucketName string) (string, error) {
	ret := _mock.Called(ctx, bucketName)

	if len(ret) == 0 {
		panic("no return value specified for BucketVersioning")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, bucketName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, bucketName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, bucketName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_BucketVersioning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BucketVersioning'
type MockBackend_BucketVersioning_Call struct {
	*mock.Call
}

// BucketVersioning is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketName string
func (_e *MockBackend_Expecter) BucketVersioning(ctx interface{}, bucketName interface{}) *MockBackend_BucketVersioning_Call {
	return &MockBackend_BucketVersioning_Call{Call: _e.mock.On("BucketVersioning", ctx, bucketName)}
}

func (_c *MockBackend_BucketVersioning_Call) Run(run func(ctx context.Context, bucketName string)) *MockBackend_BucketVersioning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_BucketVersioning_Call) Return(status string, err error) *MockBackend_BucketVersioning_Call {
	_c.Call.Return(status, err)
	return _c
}

func (_c *MockBackend_BucketVersioning_Call) RunAndReturn(run func(ctx context.Context, bucketName string) (string, error)) *MockBackend_BucketVersioning_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockBackend
func (_mock *MockBackend) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockBackend_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockBackend_Expecter) Close() *MockBackend_Close_Call {
	return &MockBackend_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockBackend_Close_Call) Run(run func()) *MockBackend_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackend_Close_Call) Return(err error) *MockBackend_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_Close_Call) RunAndReturn(run func() error) *MockBackend_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBucket provides a mock function for the type MockBackend
func (_mock *MockBackend) CreateBucket(ctx context.Context, accessKeyID string, name string) error {
	ret := _mock.Called(ctx, accessKeyID, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateBucket")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, accessKeyID, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_CreateBucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBucket'
type MockBackend_CreateBucket_Call struct {
	*mock.Call
}

// CreateBucket is a helper method to define mock.On call
//   - ctx context.Context
//   - accessKeyID string
//   - name string
func (_e *MockBackend_Expecter) CreateBucket(ctx interface{}, accessKeyID interface{}, name interface{}) *MockBackend_CreateBucket_Call {
	return &MockBackend_CreateBucket_Call{Call: _e.mock.On("CreateBucket", ctx, accessKeyID, name)}
}

func (_c *MockBackend_CreateBucket_Call) Run(run func(ctx context.Context, accessKeyID string, name string)) *MockBackend_CreateBucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_CreateBucket_Call) Return(err error) *MockBackend_CreateBucket_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_CreateBucket_Call) RunAndReturn(run func(ctx context.Context, accessKeyID string, name string) error) *MockBackend_CreateBucket_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBucket provides a mock function for the type MockBackend
func (_mock *MockBackend) DeleteBucket(ctx context.Context, accessKeyID string, name string) error {
	ret := _mock.Called(ctx, accessKeyID, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBucket")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, accessKeyID, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_DeleteBucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBucket'
type MockBackend_DeleteBucket_Call struct {
	*mock.Call
}

// DeleteBucket is a helper method to define mock.On call
//   - ctx context.Context
//   - accessKeyID string
//   - name string
func (_e *MockBackend_Expecter) DeleteBucket(ctx interface{}, accessKeyID interface{}, name interface{}) *MockBackend_DeleteBucket_Call {
	return &MockBackend_DeleteBucket_Call{Call: _e.mock.On("DeleteBucket", ctx, accessKeyID, name)}
}

func (_c *MockBackend_DeleteBucket_Call) Run(run func(ctx context.Context, accessKeyID string, name string)) *MockBackend_DeleteBucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_DeleteBucket_Call) Return(err error) *MockBackend_DeleteBucket_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_DeleteBucket_Call) RunAndReturn(run func(ctx context.Context, accessKeyID string, name string) error) *MockBackend_DeleteBucket_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBucketLifecycleConfiguration provides a mock function for the type MockBackend
func (_mock *MockBackend) DeleteBucketLifecycleConfiguration(ctx context.Context, accessKeyID string, bucket string) error {
	ret := _mock.Called(ctx, accessKeyID, bucket)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBucketLifecycleConfiguration")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, accessKeyID, bucket)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_DeleteBucketLifecycleConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBucketLifecycleConfiguration'
type MockBackend_DeleteBucketLifecycleConfiguration_Call struct {
	*mock.Call
}

// DeleteBucketLifecycleConfiguration is a helper method to define mock.On call
//   - ctx context.Context
//   - accessKeyID string
//   - bucket string
func (_e *MockBackend_Expecter) DeleteBucketLifecycleConfiguration(ctx interface{}, accessKeyID interface{}, bucket interface{}) *MockBackend_DeleteBucketLifecycleConfiguration_Call {
	return &MockBackend_DeleteBucketLifecycleConfiguration_Call{Call: _e.mock.On("DeleteBucketLifecycleConfiguration", ctx, accessKeyID, bucket)}
}

func (_c *MockBackend_DeleteBucketLifecycleConfiguration_Call) Run(run func(ctx context.Context, accessKeyID string, bucket string)) *MockBackend_DeleteBucketLifecycleConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_DeleteBucketLifecycleConfiguration_Call) Return(err error) *MockBackend_DeleteBucketLifecycleConfiguration_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_DeleteBucketLifecycleConfiguration_Call) RunAndReturn(run func(ctx context.Context, accessKeyID string, bucket string) error) *MockBackend_DeleteBucketLifecycleConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// FlushObjects provides a mock function for the type MockBackend
func (_mock *MockBackend) FlushObjects(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FlushObjects")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_FlushObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlushObjects'
type MockBackend_FlushObjects_Call struct {
	*mock.Call
}

// FlushObjects is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBackend_Expecter) FlushObjects(ctx interface{}) *MockBackend_FlushObjects_Call {
	return &MockBackend_FlushObjects_Call{Call: _e.mock.On("FlushObjects", ctx)}
}

func (_c *MockBackend_FlushObjects_Call) Run(run func(ctx context.Context)) *MockBackend_FlushObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBackend_FlushObjects_Call) Return(err error) *MockBackend_FlushObjects_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_FlushObjects_Call) RunAndReturn(run func(ctx context.Context) error) *MockBackend_FlushObjects_Call {
	_c.Call.Return(run)
	return _c
}

// GetBucketLifecycleConfiguration provides a mock function for the type MockBackend
func (_mock *MockBackend) GetBucketLifecycleConfiguration(ctx context.Context, accessKeyID string, bucket string) (s3.LifecycleConfiguration, error) {
	ret := _mock.Called(ctx, accessKeyID, bucket)

	if len(ret) == 0 {
		panic("no return value specified for GetBucketLifecycleConfiguration")
	}

	var r0 s3.LifecycleConfiguration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (s3.LifecycleConfiguration, error)); ok {
		return returnFunc(ctx, accessKeyID, bucket)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) s3.LifecycleConfiguration); ok {
		r0 = returnFunc(ctx, accessKeyID, bucket)
	} else {
		r0 = ret.Get(0).(s3.LifecycleConfiguration)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, accessKeyID, bucket)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_GetBucketLifecycleConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBucketLifecycleConfiguration'
type MockBackend_GetBucketLifecycleConfiguration_Call struct {
	*mock.Call
}

// GetBucketLifecycleConfiguration is a helper method to define mock.On call
//   - ctx context.Context
//   - accessKeyID string
//   - bucket string
func (_e *MockBackend_Expecter) GetBucketLifecycleConfiguration(ctx interface{}, accessKeyID interface{}, bucket interface{}) *MockBackend_GetBucketLifecycleConfiguration_Call {
	return &MockBackend_GetBucketLifecycleConfiguration_Call{Call: _e.mock.On("GetBucketLifecycleConfiguration", ctx, accessKeyID, bucket)}
}

func (_c *MockBackend_GetBucketLifecycleConfiguration_Call) Run(run func(ctx context.Context, accessKeyID string, bucket string)) *MockBackend_GetBucketLifecycleConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_GetBucketLifecycleConfiguration_Call) Return(lifecycleConfiguration s3.LifecycleConfiguration, err error) *MockBackend_GetBucketLifecycleConfiguration_Call {
	_c.Call.Return(lifecycleConfiguration, err)
	return _c
}

func (_c *MockBackend_GetBucketLifecycleConfiguration_Call) RunAndReturn(run func(ctx context.Context, accessKeyID string, bucket string) (s3.LifecycleConfiguration, error)) *MockBackend_GetBucketLifecycleConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// GetBucketVersioning provides a mock function for the type MockBackend
func (_mock *MockBackend) GetBucketVersioning(ctx context.Context, accessKeyID string, bucket string) (string, error) {
	ret := _mock.Called(ctx, accessKeyID, bucket)

	if len(ret) == 0 {
		panic("no return value specified for GetBucketVersioning")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, accessKeyID, bucket)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, accessKeyID, bucket)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, accessKeyID, bucket)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_GetBucketVersioning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBucketVersioning'
type MockBackend_GetBucketVersioning_Call struct {
	*mock.Call
}

// GetBucketVersioning is a helper method to define mock.On call
//   - ctx context.Context
//   - accessKeyID string
//   - bucket string
func (_e *MockBackend_Expecter) GetBucketVersioning(ctx interface{}, accessKeyID interface{}, bucket interface{}) *MockBackend_GetBucketVersioning_Call {
	return &MockBackend_GetBucketVersioning_Call{Call: _e.mock.On("GetBucketVersioning", ctx, accessKeyID, bucket)}
}

func (_c *MockBackend_GetBucketVersioning_Call) Run(run func(ctx context.Context, accessKeyID string, bucket string)) *MockBackend_GetBucketVersioning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackend_GetBucketVersioning_Call) Return(s string, err error) *MockBackend_GetBucketVersioning_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockBackend_GetBucketVersioning_Call) RunAndReturn(run func(ctx context.Context, accessKeyID string, bucket string) (string, error)) *MockBackend_GetBucketVersioning_Call {
	_c.Call.Return(run)
	return _c
}

// ListAllBuckets provides a mock function for the type MockBackend
func (_mock *MockBackend) ListAllBuckets(ctx context.Context) ([]backend.BucketInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAllBuckets")
	}

	var r0 []backend.BucketInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]backend.BucketInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []backend.BucketInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]backend.BucketInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_ListAllBuckets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllBuckets'
type MockBackend_ListAllBuckets_Call struct {
	*mock.Call
}

// ListAllBuckets is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBackend_Expecter) ListAllBuckets(ctx interface{}) *MockBackend_ListAllBuckets_Call {
	return &MockBackend_ListAllBuckets_Call{Call: _e.mock.On("ListAllBuckets", ctx)}
}

func (_c *MockBackend_ListAllBuckets_Call) Run(run func(ctx context.Context)) *MockBackend_ListAllBuckets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBackend_ListAllBuckets_Call) Return(bucketInfos []backend.BucketInfo, err error) *MockBackend_ListAllBuckets_Call {
	_c.Call.Return(bucketInfos, err)
	return _c
}

func (_c *MockBackend_ListAllBuckets_Call) RunAndReturn(run func(ctx context.Context) ([]backend.BucketInfo, error)) *MockBackend_ListAllBuckets_Call {
	_c.Call.Return(run)
	return _c
}

// ListBuckets provides a mock function for the type MockBackend
func (_mock *MockBackend) ListBuckets(ctx context.Context, accessKeyID string) ([]s3.BucketInfo, error) {
	ret := _mock.Called(ctx, accessKeyID)

	if len(ret) == 0 {
		panic("no return value specified for ListBuckets")
	}

	var r0 []s3.BucketInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]s3.BucketInfo, error)); ok {
		return returnFunc(ctx, accessKeyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []s3.BucketInfo); ok {
		r0 = returnFunc(ctx, accessKeyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]s3.BucketInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accessKeyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackend_ListBuckets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBuckets'
type MockBackend_ListBuckets_Call struct {
	*mock.Call
}

// ListBuckets is a helper method to define mock.On call
//   - ctx context.Context
//   - accessKeyID string
func (_e *MockBackend_Expecter) ListBuckets(ctx interface{}, accessKeyID interface{}) *MockBackend_ListBuckets_Call {
	return &MockBackend_ListBuckets_Call{Call: _e.mock.On("ListBuckets", ctx, accessKeyID)}
}

func (_c *MockBackend_ListBuckets_Call) Run(run func(ctx context.Context, accessKeyID string)) *MockBackend_ListBuckets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackend_ListBuckets_Call) Return(bucketInfos []s3.BucketInfo, err error) *MockBackend_ListBuckets_Call {
	_c.Call.Return(bucketInfos, err)
	return _c
}

func (_c *MockBackend_ListBuckets_Call) RunAndReturn(run func(ctx context.Context, accessKeyID string) ([]s3.BucketInfo, error)) *MockBackend_ListBuckets_Call {
	_c.Call.Return(run)
	return _c
}

// PutBucketLifecycleConfiguration provides a mock function for the type MockBackend
func (_mock *MockBackend) PutBucketLifecycleConfiguration(ctx context.Context, accessKeyID string, bucket string, config s3.LifecycleConfiguration) error {
	ret := _mock.Called(ctx, accessKeyID, bucket, config)

	if len(ret) == 0 {
		panic("no return value specified for PutBucketLifecycleConfiguration")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, s3.LifecycleConfiguration) error); ok {
		r0 = returnFunc(ctx, accessKeyID, bucket, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_PutBucketLifecycleConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutBucketLifecycleConfiguration'
type MockBackend_PutBucketLifecycleConfiguration_Call struct {
	*mock.Call
}

// PutBucketLifecycleConfiguration is a helper method to define mock.On call
//   - ctx context.Context
//   - accessKeyID string
//   - bucket string
//   - config s3.LifecycleConfiguration
func (_e *MockBackend_Expecter) PutBucketLifecycleConfiguration(ctx interface{}, accessKeyID interface{}, bucket interface{}, config interface{}) *MockBackend_PutBucketLifecycleConfiguration_Call {
	return &MockBackend_PutBucketLifecycleConfiguration_Call{Call: _e.mock.On("PutBucketLifecycleConfiguration", ctx, accessKeyID, bucket, config)}
}

func (_c *MockBackend_PutBucketLifecycleConfiguration_Call) Run(run func(ctx context.Context, accessKeyID string, bucket string, config s3.LifecycleConfiguration)) *MockBackend_PutBucketLifecycleConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 s3.LifecycleConfiguration
		if args[3] != nil {
			arg3 = args[3].(s3.LifecycleConfiguration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBackend_PutBucketLifecycleConfiguration_Call) Return(err error) *MockBackend_PutBucketLifecycleConfiguration_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_PutBucketLifecycleConfiguration_Call) RunAndReturn(run func(ctx context.Context, accessKeyID string, bucket string, config s3.LifecycleConfiguration) error) *MockBackend_PutBucketLifecycleConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// PutBucketVersioning provides a mock function for the type MockBackend
func (_mock *MockBackend) PutBucketVersioning(ctx context.Context, accessKeyID string, bucket string, status string) error {
	ret := _mock.Called(ctx, accessKeyID, bucket, status)

	if len(ret) == 0 {
		panic("no return value specified for PutBucketVersioning")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, accessKeyID, bucket, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackend_PutBucketVersioning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutBucketVersioning'
type MockBackend_PutBucketVersioning_Call struct {
	*mock.Call
}

// PutBucketVersioning is a helper method to define mock.On call
//   - ctx context.Context
//   - accessKeyID string
//   - bucket string
//   - status string
func (_e *MockBackend_Expecter) PutBucketVersioning(ctx interface{}, accessKeyID interface{}, bucket interface{}, status interface{}) *MockBackend_PutBucketVersioning_Call {
	return &MockBackend_PutBucketVersioning_Call{Call: _e.mock.On("PutBucketVersioning", ctx, accessKeyID, bucket, status)}
}

func (_c *MockBackend_PutBucketVersioning_Call) Run(run func(ctx context.Context, accessKeyID string, bucket string, status string)) *MockBackend_PutBucketVersioning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBackend_PutBucketVersioning_Call) Return(err error) *MockBackend_PutBucketVersioning_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackend_PutBucketVersioning_Call) RunAndReturn(run func(ctx context.Context, accessKeyID string, bucket string, status string) error) *MockBackend_PutBucketVersioning_Call {
	_c.Call.Return(run)
	return _c
}

// S3Backend provides a mock function for the type MockBackend
func (_mock *MockBackend) S3Backend() s3.Backend {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for S3Backend")
	}

	var r0 s3.Backend
	if returnFunc, ok := ret.Get(0).(func() s3.Backend); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(s3.Backend)
		}
	}
	return r0
}

// MockBackend_S3Backend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'S3Backend'
type MockBackend_S3Backend_Call struct {
	*mock.Call
}

// S3Backend is a helper method to define mock.On call
func (_e *MockBackend_Expecter) S3Backend() *MockBackend_S3Backend_Call {
	return &MockBackend_S3Backend_Call{Call: _e.mock.On("S3Backend")}
}

func (_c *MockBackend_S3Backend_Call) Run(run func()) *MockBackend_S3Backend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBackend_S3Backend_Call) Return(backend1 s3.Backend) *MockBackend_S3Backend_Call {
	_c.Call.Return(backend1)
	return _c
}

func (_c *MockBackend_S3Backend_Call) RunAndReturn(run func() s3.Backend) *MockBackend_S3Backend_Call {
	_c.Call.Return(run)
	return _c
}
