// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package backend

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/s3-server/internal/backend"
	"go.lumeweb.com/s3-server/internal/config"
)

// NewMockFactory creates a new instance of MockFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFactory {
	mock := &MockFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFactory is an autogenerated mock type for the Factory type
type MockFactory struct {
	mock.Mock
}

type MockFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFactory) EXPECT() *MockFactory_Expecter {
	return &MockFactory_Expecter{mock: &_m.Mock}
}

// Init provides a mock function for the type MockFactory
func (_mock *MockFactory) Init(ctx context.Context, s3Cfg config.S3Config, sqliteStore backend.S3DStore) (backend.Backend, http.Handler, func(), error) {
	ret := _mock.Called(ctx, s3Cfg, sqliteStore)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 backend.Backend
	var r1 http.Handler
	var r2 func()
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.S3Config, backend.S3DStore) (backend.Backend, http.Handler, func(), error)); ok {
		return returnFunc(ctx, s3Cfg, sqliteStore)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.S3Config, backend.S3DStore) backend.Backend); ok {
		r0 = returnFunc(ctx, s3Cfg, sqliteStore)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(backend.Backend)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, config.S3Config, backend.S3DStore) http.Handler); ok {
		r1 = returnFunc(ctx, s3Cfg, sqliteStore)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(http.Handler)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, config.S3Config, backend.S3DStore) func()); ok {
		r2 = returnFunc(ctx, s3Cfg, sqliteStore)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(func())
		}
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, config.S3Config, backend.S3DStore) error); ok {
		r3 = returnFunc(ctx, s3Cfg, sqliteStore)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockFactory_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockFactory_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
//   - s3Cfg config.S3Config
//   - sqliteStore backend.S3DStore
func (_e *MockFactory_Expecter) Init(ctx any, s3Cfg any, sqliteStore any) *MockFactory_Init_Call {
	return &MockFactory_Init_Call{Call: _e.mock.On("Init", ctx, s3Cfg, sqliteStore)}
}

func (_c *MockFactory_Init_Call) Run(run func(ctx context.Context, s3Cfg config.S3Config, sqliteStore backend.S3DStore)) *MockFactory_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 config.S3Config
		if args[1] != nil {
			arg1 = args[1].(config.S3Config)
		}
		var arg2 backend.S3DStore
		if args[2] != nil {
			arg2 = args[2].(backend.S3DStore)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFactory_Init_Call) Return(backend1 backend.Backend, handler http.Handler, fn func(), err error) *MockFactory_Init_Call {
	_c.Call.Return(backend1, handler, fn, err)
	return _c
}

func (_c *MockFactory_Init_Call) RunAndReturn(run func(ctx context.Context, s3Cfg config.S3Config, sqliteStore backend.S3DStore) (backend.Backend, http.Handler, func(), error)) *MockFactory_Init_Call {
	_c.Call.Return(run)
	return _c
}

// OpenDatabase provides a mock function for the type MockFactory
func (_mock *MockFactory) OpenDatabase(dbPath string) (backend.S3DStore, error) {
	ret := _mock.Called(dbPath)

	if len(ret) == 0 {
		panic("no return value specified for OpenDatabase")
	}

	var r0 backend.S3DStore
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (backend.S3DStore, error)); ok {
		return returnFunc(dbPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) backend.S3DStore); ok {
		r0 = returnFunc(dbPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(backend.S3DStore)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(dbPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFactory_OpenDatabase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenDatabase'
type MockFactory_OpenDatabase_Call struct {
	*mock.Call
}

// OpenDatabase is a helper method to define mock.On call
//   - dbPath string
func (_e *MockFactory_Expecter) OpenDatabase(dbPath any) *MockFactory_OpenDatabase_Call {
	return &MockFactory_OpenDatabase_Call{Call: _e.mock.On("OpenDatabase", dbPath)}
}

func (_c *MockFactory_OpenDatabase_Call) Run(run func(dbPath string)) *MockFactory_OpenDatabase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFactory_OpenDatabase_Call) Return(s3DStore backend.S3DStore, err error) *MockFactory_OpenDatabase_Call {
	_c.Call.Return(s3DStore, err)
	return _c
}

func (_c *MockFactory_OpenDatabase_Call) RunAndReturn(run func(dbPath string) (backend.S3DStore, error)) *MockFactory_OpenDatabase_Call {
	_c.Call.Return(run)
	return _c
}
