// Code generated by mockery v2.53.6. DO NOT EDIT.

package backend

import (
	backend "go.lumeweb.com/s3-server/internal/backend"
	config "go.lumeweb.com/s3-server/internal/config"

	context "context"

	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockFactory is an autogenerated mock type for the Factory type
type MockFactory struct {
	mock.Mock
}

type MockFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFactory) EXPECT() *MockFactory_Expecter {
	return &MockFactory_Expecter{mock: &_m.Mock}
}

// Init provides a mock function with given fields: ctx, s3Cfg, sqliteStore
func (_m *MockFactory) Init(ctx context.Context, s3Cfg config.S3Config, sqliteStore backend.S3DStore) (backend.Backend, http.Handler, func(), error) {
	ret := _m.Called(ctx, s3Cfg, sqliteStore)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 backend.Backend
	var r1 http.Handler
	var r2 func()
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, config.S3Config, backend.S3DStore) (backend.Backend, http.Handler, func(), error)); ok {
		return rf(ctx, s3Cfg, sqliteStore)
	}
	if rf, ok := ret.Get(0).(func(context.Context, config.S3Config, backend.S3DStore) backend.Backend); ok {
		r0 = rf(ctx, s3Cfg, sqliteStore)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(backend.Backend)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, config.S3Config, backend.S3DStore) http.Handler); ok {
		r1 = rf(ctx, s3Cfg, sqliteStore)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(http.Handler)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, config.S3Config, backend.S3DStore) func()); ok {
		r2 = rf(ctx, s3Cfg, sqliteStore)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(func())
		}
	}

	if rf, ok := ret.Get(3).(func(context.Context, config.S3Config, backend.S3DStore) error); ok {
		r3 = rf(ctx, s3Cfg, sqliteStore)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockFactory_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockFactory_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
//   - s3Cfg config.S3Config
//   - sqliteStore backend.S3DStore
func (_e *MockFactory_Expecter) Init(ctx interface{}, s3Cfg interface{}, sqliteStore interface{}) *MockFactory_Init_Call {
	return &MockFactory_Init_Call{Call: _e.mock.On("Init", ctx, s3Cfg, sqliteStore)}
}

func (_c *MockFactory_Init_Call) Run(run func(ctx context.Context, s3Cfg config.S3Config, sqliteStore backend.S3DStore)) *MockFactory_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(config.S3Config), args[2].(backend.S3DStore))
	})
	return _c
}

func (_c *MockFactory_Init_Call) Return(_a0 backend.Backend, _a1 http.Handler, _a2 func(), _a3 error) *MockFactory_Init_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockFactory_Init_Call) RunAndReturn(run func(context.Context, config.S3Config, backend.S3DStore) (backend.Backend, http.Handler, func(), error)) *MockFactory_Init_Call {
	_c.Call.Return(run)
	return _c
}

// OpenDatabase provides a mock function with given fields: dbPath
func (_m *MockFactory) OpenDatabase(dbPath string) (backend.S3DStore, error) {
	ret := _m.Called(dbPath)

	if len(ret) == 0 {
		panic("no return value specified for OpenDatabase")
	}

	var r0 backend.S3DStore
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (backend.S3DStore, error)); ok {
		return rf(dbPath)
	}
	if rf, ok := ret.Get(0).(func(string) backend.S3DStore); ok {
		r0 = rf(dbPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(backend.S3DStore)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(dbPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFactory_OpenDatabase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenDatabase'
type MockFactory_OpenDatabase_Call struct {
	*mock.Call
}

// OpenDatabase is a helper method to define mock.On call
//   - dbPath string
func (_e *MockFactory_Expecter) OpenDatabase(dbPath interface{}) *MockFactory_OpenDatabase_Call {
	return &MockFactory_OpenDatabase_Call{Call: _e.mock.On("OpenDatabase", dbPath)}
}

func (_c *MockFactory_OpenDatabase_Call) Run(run func(dbPath string)) *MockFactory_OpenDatabase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFactory_OpenDatabase_Call) Return(_a0 backend.S3DStore, _a1 error) *MockFactory_OpenDatabase_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFactory_OpenDatabase_Call) RunAndReturn(run func(string) (backend.S3DStore, error)) *MockFactory_OpenDatabase_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFactory creates a new instance of MockFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFactory {
	mock := &MockFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
