// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/s3-server/internal/backend"
	"go.sia.tech/core/types"
)

// NewMockS3DStore creates a new instance of MockS3DStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3DStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3DStore {
	mock := &MockS3DStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockS3DStore is an autogenerated mock type for the S3DStore type
type MockS3DStore struct {
	mock.Mock
}

type MockS3DStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockS3DStore) EXPECT() *MockS3DStore_Expecter {
	return &MockS3DStore_Expecter{mock: &_m.Mock}
}

// AppKey provides a mock function for the type MockS3DStore
func (_mock *MockS3DStore) AppKey() (types.PrivateKey, string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AppKey")
	}

	var r0 types.PrivateKey
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (types.PrivateKey, string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() types.PrivateKey); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.PrivateKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() string); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockS3DStore_AppKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppKey'
type MockS3DStore_AppKey_Call struct {
	*mock.Call
}

// AppKey is a helper method to define mock.On call
func (_e *MockS3DStore_Expecter) AppKey() *MockS3DStore_AppKey_Call {
	return &MockS3DStore_AppKey_Call{Call: _e.mock.On("AppKey")}
}

func (_c *MockS3DStore_AppKey_Call) Run(run func()) *MockS3DStore_AppKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockS3DStore_AppKey_Call) Return(privateKey types.PrivateKey, s string, err error) *MockS3DStore_AppKey_Call {
	_c.Call.Return(privateKey, s, err)
	return _c
}

func (_c *MockS3DStore_AppKey_Call) RunAndReturn(run func() (types.PrivateKey, string, error)) *MockS3DStore_AppKey_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockS3DStore
func (_mock *MockS3DStore) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockS3DStore_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockS3DStore_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockS3DStore_Expecter) Close() *MockS3DStore_Close_Call {
	return &MockS3DStore_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockS3DStore_Close_Call) Run(run func()) *MockS3DStore_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockS3DStore_Close_Call) Return(err error) *MockS3DStore_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockS3DStore_Close_Call) RunAndReturn(run func() error) *MockS3DStore_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAccessKey provides a mock function for the type MockS3DStore
func (_mock *MockS3DStore) CreateAccessKey(userName string, accessKeyID string, secretKey string) error {
	ret := _mock.Called(userName, accessKeyID, secretKey)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccessKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(userName, accessKeyID, secretKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockS3DStore_CreateAccessKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccessKey'
type MockS3DStore_CreateAccessKey_Call struct {
	*mock.Call
}

// CreateAccessKey is a helper method to define mock.On call
//   - userName string
//   - accessKeyID string
//   - secretKey string
func (_e *MockS3DStore_Expecter) CreateAccessKey(userName interface{}, accessKeyID interface{}, secretKey interface{}) *MockS3DStore_CreateAccessKey_Call {
	return &MockS3DStore_CreateAccessKey_Call{Call: _e.mock.On("CreateAccessKey", userName, accessKeyID, secretKey)}
}

func (_c *MockS3DStore_CreateAccessKey_Call) Run(run func(userName string, accessKeyID string, secretKey string)) *MockS3DStore_CreateAccessKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockS3DStore_CreateAccessKey_Call) Return(err error) *MockS3DStore_CreateAccessKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockS3DStore_CreateAccessKey_Call) RunAndReturn(run func(userName string, accessKeyID string, secretKey string) error) *MockS3DStore_CreateAccessKey_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockS3DStore
func (_mock *MockS3DStore) CreateUser(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockS3DStore_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockS3DStore_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - name string
func (_e *MockS3DStore_Expecter) CreateUser(name interface{}) *MockS3DStore_CreateUser_Call {
	return &MockS3DStore_CreateUser_Call{Call: _e.mock.On("CreateUser", name)}
}

func (_c *MockS3DStore_CreateUser_Call) Run(run func(name string)) *MockS3DStore_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockS3DStore_CreateUser_Call) Return(err error) *MockS3DStore_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockS3DStore_CreateUser_Call) RunAndReturn(run func(name string) error) *MockS3DStore_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccessKey provides a mock function for the type MockS3DStore
func (_mock *MockS3DStore) DeleteAccessKey(accessKeyID string) error {
	ret := _mock.Called(accessKeyID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccessKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(accessKeyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockS3DStore_DeleteAccessKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccessKey'
type MockS3DStore_DeleteAccessKey_Call struct {
	*mock.Call
}

// DeleteAccessKey is a helper method to define mock.On call
//   - accessKeyID string
func (_e *MockS3DStore_Expecter) DeleteAccessKey(accessKeyID interface{}) *MockS3DStore_DeleteAccessKey_Call {
	return &MockS3DStore_DeleteAccessKey_Call{Call: _e.mock.On("DeleteAccessKey", accessKeyID)}
}

func (_c *MockS3DStore_DeleteAccessKey_Call) Run(run func(accessKeyID string)) *MockS3DStore_DeleteAccessKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockS3DStore_DeleteAccessKey_Call) Return(err error) *MockS3DStore_DeleteAccessKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockS3DStore_DeleteAccessKey_Call) RunAndReturn(run func(accessKeyID string) error) *MockS3DStore_DeleteAccessKey_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockS3DStore
func (_mock *MockS3DStore) DeleteUser(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockS3DStore_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockS3DStore_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - name string
func (_e *MockS3DStore_Expecter) DeleteUser(name interface{}) *MockS3DStore_DeleteUser_Call {
	return &MockS3DStore_DeleteUser_Call{Call: _e.mock.On("DeleteUser", name)}
}

func (_c *MockS3DStore_DeleteUser_Call) Run(run func(name string)) *MockS3DStore_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockS3DStore_DeleteUser_Call) Return(err error) *MockS3DStore_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockS3DStore_DeleteUser_Call) RunAndReturn(run func(name string) error) *MockS3DStore_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccessKeys provides a mock function for the type MockS3DStore
func (_mock *MockS3DStore) ListAccessKeys(userName *string) ([]backend.AccessKeyInfo, error) {
	ret := _mock.Called(userName)

	if len(ret) == 0 {
		panic("no return value specified for ListAccessKeys")
	}

	var r0 []backend.AccessKeyInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*string) ([]backend.AccessKeyInfo, error)); ok {
		return returnFunc(userName)
	}
	if returnFunc, ok := ret.Get(0).(func(*string) []backend.AccessKeyInfo); ok {
		r0 = returnFunc(userName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]backend.AccessKeyInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*string) error); ok {
		r1 = returnFunc(userName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3DStore_ListAccessKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccessKeys'
type MockS3DStore_ListAccessKeys_Call struct {
	*mock.Call
}

// ListAccessKeys is a helper method to define mock.On call
//   - userName *string
func (_e *MockS3DStore_Expecter) ListAccessKeys(userName interface{}) *MockS3DStore_ListAccessKeys_Call {
	return &MockS3DStore_ListAccessKeys_Call{Call: _e.mock.On("ListAccessKeys", userName)}
}

func (_c *MockS3DStore_ListAccessKeys_Call) Run(run func(userName *string)) *MockS3DStore_ListAccessKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *string
		if args[0] != nil {
			arg0 = args[0].(*string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockS3DStore_ListAccessKeys_Call) Return(accessKeyInfos []backend.AccessKeyInfo, err error) *MockS3DStore_ListAccessKeys_Call {
	_c.Call.Return(accessKeyInfos, err)
	return _c
}

func (_c *MockS3DStore_ListAccessKeys_Call) RunAndReturn(run func(userName *string) ([]backend.AccessKeyInfo, error)) *MockS3DStore_ListAccessKeys_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function for the type MockS3DStore
func (_mock *MockS3DStore) ListUsers() ([]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3DStore_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockS3DStore_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
func (_e *MockS3DStore_Expecter) ListUsers() *MockS3DStore_ListUsers_Call {
	return &MockS3DStore_ListUsers_Call{Call: _e.mock.On("ListUsers")}
}

func (_c *MockS3DStore_ListUsers_Call) Run(run func()) *MockS3DStore_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockS3DStore_ListUsers_Call) Return(strings []string, err error) *MockS3DStore_ListUsers_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockS3DStore_ListUsers_Call) RunAndReturn(run func() ([]string, error)) *MockS3DStore_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// SetAppKey provides a mock function for the type MockS3DStore
func (_mock *MockS3DStore) SetAppKey(key types.PrivateKey, indexerURL string) error {
	ret := _mock.Called(key, indexerURL)

	if len(ret) == 0 {
		panic("no return value specified for SetAppKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(types.PrivateKey, string) error); ok {
		r0 = returnFunc(key, indexerURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockS3DStore_SetAppKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAppKey'
type MockS3DStore_SetAppKey_Call struct {
	*mock.Call
}

// SetAppKey is a helper method to define mock.On call
//   - key types.PrivateKey
//   - indexerURL string
func (_e *MockS3DStore_Expecter) SetAppKey(key interface{}, indexerURL interface{}) *MockS3DStore_SetAppKey_Call {
	return &MockS3DStore_SetAppKey_Call{Call: _e.mock.On("SetAppKey", key, indexerURL)}
}

func (_c *MockS3DStore_SetAppKey_Call) Run(run func(key types.PrivateKey, indexerURL string)) *MockS3DStore_SetAppKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.PrivateKey
		if args[0] != nil {
			arg0 = args[0].(types.PrivateKey)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockS3DStore_SetAppKey_Call) Return(err error) *MockS3DStore_SetAppKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockS3DStore_SetAppKey_Call) RunAndReturn(run func(key types.PrivateKey, indexerURL string) error) *MockS3DStore_SetAppKey_Call {
	_c.Call.Return(run)
	return _c
}
