// Code generated by mockery v2.53.6. DO NOT EDIT.

package store

import mock "github.com/stretchr/testify/mock"

// MockSessionManager is an autogenerated mock type for the SessionManager type
type MockSessionManager struct {
	mock.Mock
}

type MockSessionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionManager) EXPECT() *MockSessionManager_Expecter {
	return &MockSessionManager_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with no fields
func (_m *MockSessionManager) Create() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionManager_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionManager_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
func (_e *MockSessionManager_Expecter) Create() *MockSessionManager_Create_Call {
	return &MockSessionManager_Create_Call{Call: _e.mock.On("Create")}
}

func (_c *MockSessionManager_Create_Call) Run(run func()) *MockSessionManager_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSessionManager_Create_Call) Return(_a0 string, _a1 error) *MockSessionManager_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionManager_Create_Call) RunAndReturn(run func() (string, error)) *MockSessionManager_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: token
func (_m *MockSessionManager) Delete(token string) {
	_m.Called(token)
}

// MockSessionManager_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionManager_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - token string
func (_e *MockSessionManager_Expecter) Delete(token interface{}) *MockSessionManager_Delete_Call {
	return &MockSessionManager_Delete_Call{Call: _e.mock.On("Delete", token)}
}

func (_c *MockSessionManager_Delete_Call) Run(run func(token string)) *MockSessionManager_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSessionManager_Delete_Call) Return() *MockSessionManager_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionManager_Delete_Call) RunAndReturn(run func(string)) *MockSessionManager_Delete_Call {
	_c.Run(run)
	return _c
}

// StartCleanup provides a mock function with given fields: stop
func (_m *MockSessionManager) StartCleanup(stop <-chan struct{}) {
	_m.Called(stop)
}

// MockSessionManager_StartCleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartCleanup'
type MockSessionManager_StartCleanup_Call struct {
	*mock.Call
}

// StartCleanup is a helper method to define mock.On call
//   - stop <-chan struct{}
func (_e *MockSessionManager_Expecter) StartCleanup(stop interface{}) *MockSessionManager_StartCleanup_Call {
	return &MockSessionManager_StartCleanup_Call{Call: _e.mock.On("StartCleanup", stop)}
}

func (_c *MockSessionManager_StartCleanup_Call) Run(run func(stop <-chan struct{})) *MockSessionManager_StartCleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(<-chan struct{}))
	})
	return _c
}

func (_c *MockSessionManager_StartCleanup_Call) Return() *MockSessionManager_StartCleanup_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionManager_StartCleanup_Call) RunAndReturn(run func(<-chan struct{})) *MockSessionManager_StartCleanup_Call {
	_c.Run(run)
	return _c
}

// Validate provides a mock function with given fields: token
func (_m *MockSessionManager) Validate(token string) bool {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockSessionManager_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockSessionManager_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - token string
func (_e *MockSessionManager_Expecter) Validate(token interface{}) *MockSessionManager_Validate_Call {
	return &MockSessionManager_Validate_Call{Call: _e.mock.On("Validate", token)}
}

func (_c *MockSessionManager_Validate_Call) Run(run func(token string)) *MockSessionManager_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSessionManager_Validate_Call) Return(_a0 bool) *MockSessionManager_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionManager_Validate_Call) RunAndReturn(run func(string) bool) *MockSessionManager_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionManager creates a new instance of MockSessionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionManager {
	mock := &MockSessionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
