// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/s3-server/internal/config"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// AccessKeys provides a mock function for the type MockStore
func (_mock *MockStore) AccessKeys() []config.KeyPair {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AccessKeys")
	}

	var r0 []config.KeyPair
	if returnFunc, ok := ret.Get(0).(func() []config.KeyPair); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.KeyPair)
		}
	}
	return r0
}

// MockStore_AccessKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccessKeys'
type MockStore_AccessKeys_Call struct {
	*mock.Call
}

// AccessKeys is a helper method to define mock.On call
func (_e *MockStore_Expecter) AccessKeys() *MockStore_AccessKeys_Call {
	return &MockStore_AccessKeys_Call{Call: _e.mock.On("AccessKeys")}
}

func (_c *MockStore_AccessKeys_Call) Run(run func()) *MockStore_AccessKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_AccessKeys_Call) Return(keyPairs []config.KeyPair) *MockStore_AccessKeys_Call {
	_c.Call.Return(keyPairs)
	return _c
}

func (_c *MockStore_AccessKeys_Call) RunAndReturn(run func() []config.KeyPair) *MockStore_AccessKeys_Call {
	_c.Call.Return(run)
	return _c
}

// ClearAdminPassword provides a mock function for the type MockStore
func (_mock *MockStore) ClearAdminPassword() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClearAdminPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_ClearAdminPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearAdminPassword'
type MockStore_ClearAdminPassword_Call struct {
	*mock.Call
}

// ClearAdminPassword is a helper method to define mock.On call
func (_e *MockStore_Expecter) ClearAdminPassword() *MockStore_ClearAdminPassword_Call {
	return &MockStore_ClearAdminPassword_Call{Call: _e.mock.On("ClearAdminPassword")}
}

func (_c *MockStore_ClearAdminPassword_Call) Run(run func()) *MockStore_ClearAdminPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_ClearAdminPassword_Call) Return(err error) *MockStore_ClearAdminPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_ClearAdminPassword_Call) RunAndReturn(run func() error) *MockStore_ClearAdminPassword_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function for the type MockStore
func (_mock *MockStore) Config() config.PanelConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.PanelConfig
	if returnFunc, ok := ret.Get(0).(func() config.PanelConfig); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(config.PanelConfig)
	}
	return r0
}

// MockStore_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockStore_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockStore_Expecter) Config() *MockStore_Config_Call {
	return &MockStore_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockStore_Config_Call) Run(run func()) *MockStore_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_Config_Call) Return(panelConfig config.PanelConfig) *MockStore_Config_Call {
	_c.Call.Return(panelConfig)
	return _c
}

func (_c *MockStore_Config_Call) RunAndReturn(run func() config.PanelConfig) *MockStore_Config_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function for the type MockStore
func (_mock *MockStore) CreateSession() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockStore_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
func (_e *MockStore_Expecter) CreateSession() *MockStore_CreateSession_Call {
	return &MockStore_CreateSession_Call{Call: _e.mock.On("CreateSession")}
}

func (_c *MockStore_CreateSession_Call) Run(run func()) *MockStore_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_CreateSession_Call) Return(s string, err error) *MockStore_CreateSession_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStore_CreateSession_Call) RunAndReturn(run func() (string, error)) *MockStore_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DataDir provides a mock function for the type MockStore
func (_mock *MockStore) DataDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DataDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockStore_DataDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DataDir'
type MockStore_DataDir_Call struct {
	*mock.Call
}

// DataDir is a helper method to define mock.On call
func (_e *MockStore_Expecter) DataDir() *MockStore_DataDir_Call {
	return &MockStore_DataDir_Call{Call: _e.mock.On("DataDir")}
}

func (_c *MockStore_DataDir_Call) Run(run func()) *MockStore_DataDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_DataDir_Call) Return(s string) *MockStore_DataDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockStore_DataDir_Call) RunAndReturn(run func() string) *MockStore_DataDir_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSession provides a mock function for the type MockStore
func (_mock *MockStore) DeleteSession(token string) {
	_mock.Called(token)
	return
}

// MockStore_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockStore_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - token string
func (_e *MockStore_Expecter) DeleteSession(token interface{}) *MockStore_DeleteSession_Call {
	return &MockStore_DeleteSession_Call{Call: _e.mock.On("DeleteSession", token)}
}

func (_c *MockStore_DeleteSession_Call) Run(run func(token string)) *MockStore_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_DeleteSession_Call) Return() *MockStore_DeleteSession_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStore_DeleteSession_Call) RunAndReturn(run func(token string)) *MockStore_DeleteSession_Call {
	_c.Run(run)
	return _c
}

// LogConfig provides a mock function for the type MockStore
func (_mock *MockStore) LogConfig() config.LogConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LogConfig")
	}

	var r0 config.LogConfig
	if returnFunc, ok := ret.Get(0).(func() config.LogConfig); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(config.LogConfig)
	}
	return r0
}

// MockStore_LogConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogConfig'
type MockStore_LogConfig_Call struct {
	*mock.Call
}

// LogConfig is a helper method to define mock.On call
func (_e *MockStore_Expecter) LogConfig() *MockStore_LogConfig_Call {
	return &MockStore_LogConfig_Call{Call: _e.mock.On("LogConfig")}
}

func (_c *MockStore_LogConfig_Call) Run(run func()) *MockStore_LogConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_LogConfig_Call) Return(logConfig config.LogConfig) *MockStore_LogConfig_Call {
	_c.Call.Return(logConfig)
	return _c
}

func (_c *MockStore_LogConfig_Call) RunAndReturn(run func() config.LogConfig) *MockStore_LogConfig_Call {
	_c.Call.Return(run)
	return _c
}

// OnboardingState provides a mock function for the type MockStore
func (_mock *MockStore) OnboardingState() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OnboardingState")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockStore_OnboardingState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnboardingState'
type MockStore_OnboardingState_Call struct {
	*mock.Call
}

// OnboardingState is a helper method to define mock.On call
func (_e *MockStore_Expecter) OnboardingState() *MockStore_OnboardingState_Call {
	return &MockStore_OnboardingState_Call{Call: _e.mock.On("OnboardingState")}
}

func (_c *MockStore_OnboardingState_Call) Run(run func()) *MockStore_OnboardingState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_OnboardingState_Call) Return(s string) *MockStore_OnboardingState_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockStore_OnboardingState_Call) RunAndReturn(run func() string) *MockStore_OnboardingState_Call {
	_c.Call.Return(run)
	return _c
}

// ResetTokenPath provides a mock function for the type MockStore
func (_mock *MockStore) ResetTokenPath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResetTokenPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockStore_ResetTokenPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetTokenPath'
type MockStore_ResetTokenPath_Call struct {
	*mock.Call
}

// ResetTokenPath is a helper method to define mock.On call
func (_e *MockStore_Expecter) ResetTokenPath() *MockStore_ResetTokenPath_Call {
	return &MockStore_ResetTokenPath_Call{Call: _e.mock.On("ResetTokenPath")}
}

func (_c *MockStore_ResetTokenPath_Call) Run(run func()) *MockStore_ResetTokenPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_ResetTokenPath_Call) Return(s string) *MockStore_ResetTokenPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockStore_ResetTokenPath_Call) RunAndReturn(run func() string) *MockStore_ResetTokenPath_Call {
	_c.Call.Return(run)
	return _c
}

// S3Config provides a mock function for the type MockStore
func (_mock *MockStore) S3Config() config.S3Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for S3Config")
	}

	var r0 config.S3Config
	if returnFunc, ok := ret.Get(0).(func() config.S3Config); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(config.S3Config)
	}
	return r0
}

// MockStore_S3Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'S3Config'
type MockStore_S3Config_Call struct {
	*mock.Call
}

// S3Config is a helper method to define mock.On call
func (_e *MockStore_Expecter) S3Config() *MockStore_S3Config_Call {
	return &MockStore_S3Config_Call{Call: _e.mock.On("S3Config")}
}

func (_c *MockStore_S3Config_Call) Run(run func()) *MockStore_S3Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_S3Config_Call) Return(s3Config config.S3Config) *MockStore_S3Config_Call {
	_c.Call.Return(s3Config)
	return _c
}

func (_c *MockStore_S3Config_Call) RunAndReturn(run func() config.S3Config) *MockStore_S3Config_Call {
	_c.Call.Return(run)
	return _c
}

// SSLConfig provides a mock function for the type MockStore
func (_mock *MockStore) SSLConfig() config.SSLConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SSLConfig")
	}

	var r0 config.SSLConfig
	if returnFunc, ok := ret.Get(0).(func() config.SSLConfig); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(config.SSLConfig)
	}
	return r0
}

// MockStore_SSLConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SSLConfig'
type MockStore_SSLConfig_Call struct {
	*mock.Call
}

// SSLConfig is a helper method to define mock.On call
func (_e *MockStore_Expecter) SSLConfig() *MockStore_SSLConfig_Call {
	return &MockStore_SSLConfig_Call{Call: _e.mock.On("SSLConfig")}
}

func (_c *MockStore_SSLConfig_Call) Run(run func()) *MockStore_SSLConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_SSLConfig_Call) Return(sSLConfig config.SSLConfig) *MockStore_SSLConfig_Call {
	_c.Call.Return(sSLConfig)
	return _c
}

func (_c *MockStore_SSLConfig_Call) RunAndReturn(run func() config.SSLConfig) *MockStore_SSLConfig_Call {
	_c.Call.Return(run)
	return _c
}

// SetAccessKeys provides a mock function for the type MockStore
func (_mock *MockStore) SetAccessKeys(keys []config.KeyPair) error {
	ret := _mock.Called(keys)

	if len(ret) == 0 {
		panic("no return value specified for SetAccessKeys")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]config.KeyPair) error); ok {
		r0 = returnFunc(keys)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_SetAccessKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAccessKeys'
type MockStore_SetAccessKeys_Call struct {
	*mock.Call
}

// SetAccessKeys is a helper method to define mock.On call
//   - keys []config.KeyPair
func (_e *MockStore_Expecter) SetAccessKeys(keys interface{}) *MockStore_SetAccessKeys_Call {
	return &MockStore_SetAccessKeys_Call{Call: _e.mock.On("SetAccessKeys", keys)}
}

func (_c *MockStore_SetAccessKeys_Call) Run(run func(keys []config.KeyPair)) *MockStore_SetAccessKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []config.KeyPair
		if args[0] != nil {
			arg0 = args[0].([]config.KeyPair)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_SetAccessKeys_Call) Return(err error) *MockStore_SetAccessKeys_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_SetAccessKeys_Call) RunAndReturn(run func(keys []config.KeyPair) error) *MockStore_SetAccessKeys_Call {
	_c.Call.Return(run)
	return _c
}

// SetAdminPassword provides a mock function for the type MockStore
func (_mock *MockStore) SetAdminPassword(password string) error {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for SetAdminPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_SetAdminPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAdminPassword'
type MockStore_SetAdminPassword_Call struct {
	*mock.Call
}

// SetAdminPassword is a helper method to define mock.On call
//   - password string
func (_e *MockStore_Expecter) SetAdminPassword(password interface{}) *MockStore_SetAdminPassword_Call {
	return &MockStore_SetAdminPassword_Call{Call: _e.mock.On("SetAdminPassword", password)}
}

func (_c *MockStore_SetAdminPassword_Call) Run(run func(password string)) *MockStore_SetAdminPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_SetAdminPassword_Call) Return(err error) *MockStore_SetAdminPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_SetAdminPassword_Call) RunAndReturn(run func(password string) error) *MockStore_SetAdminPassword_Call {
	_c.Call.Return(run)
	return _c
}

// SetLogConfig provides a mock function for the type MockStore
func (_mock *MockStore) SetLogConfig(cfg config.LogConfig) error {
	ret := _mock.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for SetLogConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(config.LogConfig) error); ok {
		r0 = returnFunc(cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_SetLogConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogConfig'
type MockStore_SetLogConfig_Call struct {
	*mock.Call
}

// SetLogConfig is a helper method to define mock.On call
//   - cfg config.LogConfig
func (_e *MockStore_Expecter) SetLogConfig(cfg interface{}) *MockStore_SetLogConfig_Call {
	return &MockStore_SetLogConfig_Call{Call: _e.mock.On("SetLogConfig", cfg)}
}

func (_c *MockStore_SetLogConfig_Call) Run(run func(cfg config.LogConfig)) *MockStore_SetLogConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.LogConfig
		if args[0] != nil {
			arg0 = args[0].(config.LogConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_SetLogConfig_Call) Return(err error) *MockStore_SetLogConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_SetLogConfig_Call) RunAndReturn(run func(cfg config.LogConfig) error) *MockStore_SetLogConfig_Call {
	_c.Call.Return(run)
	return _c
}

// SetOnboardingState provides a mock function for the type MockStore
func (_mock *MockStore) SetOnboardingState(state string) error {
	ret := _mock.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for SetOnboardingState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_SetOnboardingState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOnboardingState'
type MockStore_SetOnboardingState_Call struct {
	*mock.Call
}

// SetOnboardingState is a helper method to define mock.On call
//   - state string
func (_e *MockStore_Expecter) SetOnboardingState(state interface{}) *MockStore_SetOnboardingState_Call {
	return &MockStore_SetOnboardingState_Call{Call: _e.mock.On("SetOnboardingState", state)}
}

func (_c *MockStore_SetOnboardingState_Call) Run(run func(state string)) *MockStore_SetOnboardingState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_SetOnboardingState_Call) Return(err error) *MockStore_SetOnboardingState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_SetOnboardingState_Call) RunAndReturn(run func(state string) error) *MockStore_SetOnboardingState_Call {
	_c.Call.Return(run)
	return _c
}

// SetS3Config provides a mock function for the type MockStore
func (_mock *MockStore) SetS3Config(cfg config.S3Config) error {
	ret := _mock.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for SetS3Config")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(config.S3Config) error); ok {
		r0 = returnFunc(cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_SetS3Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetS3Config'
type MockStore_SetS3Config_Call struct {
	*mock.Call
}

// SetS3Config is a helper method to define mock.On call
//   - cfg config.S3Config
func (_e *MockStore_Expecter) SetS3Config(cfg interface{}) *MockStore_SetS3Config_Call {
	return &MockStore_SetS3Config_Call{Call: _e.mock.On("SetS3Config", cfg)}
}

func (_c *MockStore_SetS3Config_Call) Run(run func(cfg config.S3Config)) *MockStore_SetS3Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.S3Config
		if args[0] != nil {
			arg0 = args[0].(config.S3Config)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_SetS3Config_Call) Return(err error) *MockStore_SetS3Config_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_SetS3Config_Call) RunAndReturn(run func(cfg config.S3Config) error) *MockStore_SetS3Config_Call {
	_c.Call.Return(run)
	return _c
}

// SetSSLConfig provides a mock function for the type MockStore
func (_mock *MockStore) SetSSLConfig(cfg config.SSLConfig) error {
	ret := _mock.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for SetSSLConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(config.SSLConfig) error); ok {
		r0 = returnFunc(cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_SetSSLConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSSLConfig'
type MockStore_SetSSLConfig_Call struct {
	*mock.Call
}

// SetSSLConfig is a helper method to define mock.On call
//   - cfg config.SSLConfig
func (_e *MockStore_Expecter) SetSSLConfig(cfg interface{}) *MockStore_SetSSLConfig_Call {
	return &MockStore_SetSSLConfig_Call{Call: _e.mock.On("SetSSLConfig", cfg)}
}

func (_c *MockStore_SetSSLConfig_Call) Run(run func(cfg config.SSLConfig)) *MockStore_SetSSLConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.SSLConfig
		if args[0] != nil {
			arg0 = args[0].(config.SSLConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_SetSSLConfig_Call) Return(err error) *MockStore_SetSSLConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_SetSSLConfig_Call) RunAndReturn(run func(cfg config.SSLConfig) error) *MockStore_SetSSLConfig_Call {
	_c.Call.Return(run)
	return _c
}

// StartSessionCleanup provides a mock function for the type MockStore
func (_mock *MockStore) StartSessionCleanup(stop <-chan struct{}) {
	_mock.Called(stop)
	return
}

// MockStore_StartSessionCleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartSessionCleanup'
type MockStore_StartSessionCleanup_Call struct {
	*mock.Call
}

// StartSessionCleanup is a helper method to define mock.On call
//   - stop <-chan struct{}
func (_e *MockStore_Expecter) StartSessionCleanup(stop interface{}) *MockStore_StartSessionCleanup_Call {
	return &MockStore_StartSessionCleanup_Call{Call: _e.mock.On("StartSessionCleanup", stop)}
}

func (_c *MockStore_StartSessionCleanup_Call) Run(run func(stop <-chan struct{})) *MockStore_StartSessionCleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 <-chan struct{}
		if args[0] != nil {
			arg0 = args[0].(<-chan struct{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_StartSessionCleanup_Call) Return() *MockStore_StartSessionCleanup_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStore_StartSessionCleanup_Call) RunAndReturn(run func(stop <-chan struct{})) *MockStore_StartSessionCleanup_Call {
	_c.Run(run)
	return _c
}

// ValidateAdminPassword provides a mock function for the type MockStore
func (_mock *MockStore) ValidateAdminPassword(password string) bool {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAdminPassword")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockStore_ValidateAdminPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAdminPassword'
type MockStore_ValidateAdminPassword_Call struct {
	*mock.Call
}

// ValidateAdminPassword is a helper method to define mock.On call
//   - password string
func (_e *MockStore_Expecter) ValidateAdminPassword(password interface{}) *MockStore_ValidateAdminPassword_Call {
	return &MockStore_ValidateAdminPassword_Call{Call: _e.mock.On("ValidateAdminPassword", password)}
}

func (_c *MockStore_ValidateAdminPassword_Call) Run(run func(password string)) *MockStore_ValidateAdminPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_ValidateAdminPassword_Call) Return(b bool) *MockStore_ValidateAdminPassword_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockStore_ValidateAdminPassword_Call) RunAndReturn(run func(password string) bool) *MockStore_ValidateAdminPassword_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateSession provides a mock function for the type MockStore
func (_mock *MockStore) ValidateSession(token string) bool {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateSession")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockStore_ValidateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateSession'
type MockStore_ValidateSession_Call struct {
	*mock.Call
}

// ValidateSession is a helper method to define mock.On call
//   - token string
func (_e *MockStore_Expecter) ValidateSession(token interface{}) *MockStore_ValidateSession_Call {
	return &MockStore_ValidateSession_Call{Call: _e.mock.On("ValidateSession", token)}
}

func (_c *MockStore_ValidateSession_Call) Run(run func(token string)) *MockStore_ValidateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_ValidateSession_Call) Return(b bool) *MockStore_ValidateSession_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockStore_ValidateSession_Call) RunAndReturn(run func(token string) bool) *MockStore_ValidateSession_Call {
	_c.Call.Return(run)
	return _c
}
