// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/s3-server/internal/version"
)

// NewMockChecker creates a new instance of MockChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChecker {
	mock := &MockChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChecker is an autogenerated mock type for the Checker type
type MockChecker struct {
	mock.Mock
}

type MockChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChecker) EXPECT() *MockChecker_Expecter {
	return &MockChecker_Expecter{mock: &_m.Mock}
}

// Result provides a mock function for the type MockChecker
func (_mock *MockChecker) Result() version.CheckResult {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Result")
	}

	var r0 version.CheckResult
	if returnFunc, ok := ret.Get(0).(func() version.CheckResult); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(version.CheckResult)
	}
	return r0
}

// MockChecker_Result_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Result'
type MockChecker_Result_Call struct {
	*mock.Call
}

// Result is a helper method to define mock.On call
func (_e *MockChecker_Expecter) Result() *MockChecker_Result_Call {
	return &MockChecker_Result_Call{Call: _e.mock.On("Result")}
}

func (_c *MockChecker_Result_Call) Run(run func()) *MockChecker_Result_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChecker_Result_Call) Return(checkResult version.CheckResult) *MockChecker_Result_Call {
	_c.Call.Return(checkResult)
	return _c
}

func (_c *MockChecker_Result_Call) RunAndReturn(run func() version.CheckResult) *MockChecker_Result_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockChecker
func (_mock *MockChecker) Start(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockChecker_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockChecker_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockChecker_Expecter) Start(ctx interface{}) *MockChecker_Start_Call {
	return &MockChecker_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockChecker_Start_Call) Run(run func(ctx context.Context)) *MockChecker_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChecker_Start_Call) Return() *MockChecker_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChecker_Start_Call) RunAndReturn(run func(ctx context.Context)) *MockChecker_Start_Call {
	_c.Run(run)
	return _c
}
