// Code generated by mockery v2.53.6. DO NOT EDIT.

package store

import (
	context "context"

	backend "go.lumeweb.com/s3-server/internal/backend"

	mock "github.com/stretchr/testify/mock"
)

// MockBackendInitializer is an autogenerated mock type for the BackendInitializer type
type MockBackendInitializer struct {
	mock.Mock
}

type MockBackendInitializer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackendInitializer) EXPECT() *MockBackendInitializer_Expecter {
	return &MockBackendInitializer_Expecter{mock: &_m.Mock}
}

// InitAfterOnboarding provides a mock function with given fields: ctx, sqliteStore
func (_m *MockBackendInitializer) InitAfterOnboarding(ctx context.Context, sqliteStore backend.S3DStore) error {
	ret := _m.Called(ctx, sqliteStore)

	if len(ret) == 0 {
		panic("no return value specified for InitAfterOnboarding")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, backend.S3DStore) error); ok {
		r0 = rf(ctx, sqliteStore)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBackendInitializer_InitAfterOnboarding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitAfterOnboarding'
type MockBackendInitializer_InitAfterOnboarding_Call struct {
	*mock.Call
}

// InitAfterOnboarding is a helper method to define mock.On call
//   - ctx context.Context
//   - sqliteStore backend.S3DStore
func (_e *MockBackendInitializer_Expecter) InitAfterOnboarding(ctx interface{}, sqliteStore interface{}) *MockBackendInitializer_InitAfterOnboarding_Call {
	return &MockBackendInitializer_InitAfterOnboarding_Call{Call: _e.mock.On("InitAfterOnboarding", ctx, sqliteStore)}
}

func (_c *MockBackendInitializer_InitAfterOnboarding_Call) Run(run func(ctx context.Context, sqliteStore backend.S3DStore)) *MockBackendInitializer_InitAfterOnboarding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(backend.S3DStore))
	})
	return _c
}

func (_c *MockBackendInitializer_InitAfterOnboarding_Call) Return(_a0 error) *MockBackendInitializer_InitAfterOnboarding_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBackendInitializer_InitAfterOnboarding_Call) RunAndReturn(run func(context.Context, backend.S3DStore) error) *MockBackendInitializer_InitAfterOnboarding_Call {
	_c.Call.Return(run)
	return _c
}

// OpenDatabase provides a mock function with given fields: dbPath
func (_m *MockBackendInitializer) OpenDatabase(dbPath string) (backend.S3DStore, error) {
	ret := _m.Called(dbPath)

	if len(ret) == 0 {
		panic("no return value specified for OpenDatabase")
	}

	var r0 backend.S3DStore
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (backend.S3DStore, error)); ok {
		return rf(dbPath)
	}
	if rf, ok := ret.Get(0).(func(string) backend.S3DStore); ok {
		r0 = rf(dbPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(backend.S3DStore)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(dbPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBackendInitializer_OpenDatabase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenDatabase'
type MockBackendInitializer_OpenDatabase_Call struct {
	*mock.Call
}

// OpenDatabase is a helper method to define mock.On call
//   - dbPath string
func (_e *MockBackendInitializer_Expecter) OpenDatabase(dbPath interface{}) *MockBackendInitializer_OpenDatabase_Call {
	return &MockBackendInitializer_OpenDatabase_Call{Call: _e.mock.On("OpenDatabase", dbPath)}
}

func (_c *MockBackendInitializer_OpenDatabase_Call) Run(run func(dbPath string)) *MockBackendInitializer_OpenDatabase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockBackendInitializer_OpenDatabase_Call) Return(_a0 backend.S3DStore, _a1 error) *MockBackendInitializer_OpenDatabase_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBackendInitializer_OpenDatabase_Call) RunAndReturn(run func(string) (backend.S3DStore, error)) *MockBackendInitializer_OpenDatabase_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBackendInitializer creates a new instance of MockBackendInitializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackendInitializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackendInitializer {
	mock := &MockBackendInitializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
