// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/s3-server/internal/backend"
)

// NewMockBackendInitializer creates a new instance of MockBackendInitializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackendInitializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackendInitializer {
	mock := &MockBackendInitializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBackendInitializer is an autogenerated mock type for the BackendInitializer type
type MockBackendInitializer struct {
	mock.Mock
}

type MockBackendInitializer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackendInitializer) EXPECT() *MockBackendInitializer_Expecter {
	return &MockBackendInitializer_Expecter{mock: &_m.Mock}
}

// InitAfterOnboardingAsync provides a mock function for the type MockBackendInitializer
func (_mock *MockBackendInitializer) InitAfterOnboardingAsync(ctx context.Context, sqliteStore backend.S3DStore, onFailure func()) {
	_mock.Called(ctx, sqliteStore, onFailure)
	return
}

// MockBackendInitializer_InitAfterOnboardingAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitAfterOnboardingAsync'
type MockBackendInitializer_InitAfterOnboardingAsync_Call struct {
	*mock.Call
}

// InitAfterOnboardingAsync is a helper method to define mock.On call
//   - ctx context.Context
//   - sqliteStore backend.S3DStore
//   - onFailure func()
func (_e *MockBackendInitializer_Expecter) InitAfterOnboardingAsync(ctx interface{}, sqliteStore interface{}, onFailure interface{}) *MockBackendInitializer_InitAfterOnboardingAsync_Call {
	return &MockBackendInitializer_InitAfterOnboardingAsync_Call{Call: _e.mock.On("InitAfterOnboardingAsync", ctx, sqliteStore, onFailure)}
}

func (_c *MockBackendInitializer_InitAfterOnboardingAsync_Call) Run(run func(ctx context.Context, sqliteStore backend.S3DStore, onFailure func())) *MockBackendInitializer_InitAfterOnboardingAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 backend.S3DStore
		if args[1] != nil {
			arg1 = args[1].(backend.S3DStore)
		}
		var arg2 func()
		if args[2] != nil {
			arg2 = args[2].(func())
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBackendInitializer_InitAfterOnboardingAsync_Call) Return() *MockBackendInitializer_InitAfterOnboardingAsync_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBackendInitializer_InitAfterOnboardingAsync_Call) RunAndReturn(run func(ctx context.Context, sqliteStore backend.S3DStore, onFailure func())) *MockBackendInitializer_InitAfterOnboardingAsync_Call {
	_c.Run(run)
	return _c
}

// OpenDatabase provides a mock function for the type MockBackendInitializer
func (_mock *MockBackendInitializer) OpenDatabase(dbPath string) (backend.S3DStore, error) {
	ret := _mock.Called(dbPath)

	if len(ret) == 0 {
		panic("no return value specified for OpenDatabase")
	}

	var r0 backend.S3DStore
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (backend.S3DStore, error)); ok {
		return returnFunc(dbPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) backend.S3DStore); ok {
		r0 = returnFunc(dbPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(backend.S3DStore)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(dbPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBackendInitializer_OpenDatabase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenDatabase'
type MockBackendInitializer_OpenDatabase_Call struct {
	*mock.Call
}

// OpenDatabase is a helper method to define mock.On call
//   - dbPath string
func (_e *MockBackendInitializer_Expecter) OpenDatabase(dbPath interface{}) *MockBackendInitializer_OpenDatabase_Call {
	return &MockBackendInitializer_OpenDatabase_Call{Call: _e.mock.On("OpenDatabase", dbPath)}
}

func (_c *MockBackendInitializer_OpenDatabase_Call) Run(run func(dbPath string)) *MockBackendInitializer_OpenDatabase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBackendInitializer_OpenDatabase_Call) Return(s3DStore backend.S3DStore, err error) *MockBackendInitializer_OpenDatabase_Call {
	_c.Call.Return(s3DStore, err)
	return _c
}

func (_c *MockBackendInitializer_OpenDatabase_Call) RunAndReturn(run func(dbPath string) (backend.S3DStore, error)) *MockBackendInitializer_OpenDatabase_Call {
	_c.Call.Return(run)
	return _c
}
