// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBackendRestarter creates a new instance of MockBackendRestarter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackendRestarter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackendRestarter {
	mock := &MockBackendRestarter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBackendRestarter is an autogenerated mock type for the BackendRestarter type
type MockBackendRestarter struct {
	mock.Mock
}

type MockBackendRestarter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackendRestarter) EXPECT() *MockBackendRestarter_Expecter {
	return &MockBackendRestarter_Expecter{mock: &_m.Mock}
}

// Restart provides a mock function for the type MockBackendRestarter
func (_mock *MockBackendRestarter) Restart(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Restart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBackendRestarter_Restart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restart'
type MockBackendRestarter_Restart_Call struct {
	*mock.Call
}

// Restart is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBackendRestarter_Expecter) Restart(ctx any) *MockBackendRestarter_Restart_Call {
	return &MockBackendRestarter_Restart_Call{Call: _e.mock.On("Restart", ctx)}
}

func (_c *MockBackendRestarter_Restart_Call) Run(run func(ctx context.Context)) *MockBackendRestarter_Restart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBackendRestarter_Restart_Call) Return(err error) *MockBackendRestarter_Restart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBackendRestarter_Restart_Call) RunAndReturn(run func(ctx context.Context) error) *MockBackendRestarter_Restart_Call {
	_c.Call.Return(run)
	return _c
}
