// Code generated by mockery v2.53.6. DO NOT EDIT.

package handlersmocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockS3Swapper is an autogenerated mock type for the S3Swapper type
type MockS3Swapper struct {
	mock.Mock
}

type MockS3Swapper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockS3Swapper) EXPECT() *MockS3Swapper_Expecter {
	return &MockS3Swapper_Expecter{mock: &_m.Mock}
}

// Swap provides a mock function with given fields: handler
func (_m *MockS3Swapper) Swap(handler http.Handler) {
	_m.Called(handler)
}

// MockS3Swapper_Swap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Swap'
type MockS3Swapper_Swap_Call struct {
	*mock.Call
}

// Swap is a helper method to define mock.On call
//   - handler http.Handler
func (_e *MockS3Swapper_Expecter) Swap(handler interface{}) *MockS3Swapper_Swap_Call {
	return &MockS3Swapper_Swap_Call{Call: _e.mock.On("Swap", handler)}
}

func (_c *MockS3Swapper_Swap_Call) Run(run func(handler http.Handler)) *MockS3Swapper_Swap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Handler))
	})
	return _c
}

func (_c *MockS3Swapper_Swap_Call) Return() *MockS3Swapper_Swap_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockS3Swapper_Swap_Call) RunAndReturn(run func(http.Handler)) *MockS3Swapper_Swap_Call {
	_c.Run(run)
	return _c
}

// NewMockS3Swapper creates a new instance of MockS3Swapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3Swapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3Swapper {
	mock := &MockS3Swapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
