// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockS3Swapper creates a new instance of MockS3Swapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3Swapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3Swapper {
	mock := &MockS3Swapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockS3Swapper is an autogenerated mock type for the S3Swapper type
type MockS3Swapper struct {
	mock.Mock
}

type MockS3Swapper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockS3Swapper) EXPECT() *MockS3Swapper_Expecter {
	return &MockS3Swapper_Expecter{mock: &_m.Mock}
}

// Swap provides a mock function for the type MockS3Swapper
func (_mock *MockS3Swapper) Swap(handler http.Handler) {
	_mock.Called(handler)
	return
}

// MockS3Swapper_Swap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Swap'
type MockS3Swapper_Swap_Call struct {
	*mock.Call
}

// Swap is a helper method to define mock.On call
//   - handler http.Handler
func (_e *MockS3Swapper_Expecter) Swap(handler any) *MockS3Swapper_Swap_Call {
	return &MockS3Swapper_Swap_Call{Call: _e.mock.On("Swap", handler)}
}

func (_c *MockS3Swapper_Swap_Call) Run(run func(handler http.Handler)) *MockS3Swapper_Swap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.Handler
		if args[0] != nil {
			arg0 = args[0].(http.Handler)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockS3Swapper_Swap_Call) Return() *MockS3Swapper_Swap_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockS3Swapper_Swap_Call) RunAndReturn(run func(handler http.Handler)) *MockS3Swapper_Swap_Call {
	_c.Run(run)
	return _c
}
