// Code generated by mockery v2.53.6. DO NOT EDIT.

package handlers

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockSSEBroker is an autogenerated mock type for the SSEBroker type
type MockSSEBroker struct {
	mock.Mock
}

type MockSSEBroker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSSEBroker) EXPECT() *MockSSEBroker_Expecter {
	return &MockSSEBroker_Expecter{mock: &_m.Mock}
}

// NotifyBucketChange provides a mock function with given fields: action, name
func (_m *MockSSEBroker) NotifyBucketChange(action string, name string) {
	_m.Called(action, name)
}

// MockSSEBroker_NotifyBucketChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyBucketChange'
type MockSSEBroker_NotifyBucketChange_Call struct {
	*mock.Call
}

// NotifyBucketChange is a helper method to define mock.On call
//   - action string
//   - name string
func (_e *MockSSEBroker_Expecter) NotifyBucketChange(action interface{}, name interface{}) *MockSSEBroker_NotifyBucketChange_Call {
	return &MockSSEBroker_NotifyBucketChange_Call{Call: _e.mock.On("NotifyBucketChange", action, name)}
}

func (_c *MockSSEBroker_NotifyBucketChange_Call) Run(run func(action string, name string)) *MockSSEBroker_NotifyBucketChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockSSEBroker_NotifyBucketChange_Call) Return() *MockSSEBroker_NotifyBucketChange_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSSEBroker_NotifyBucketChange_Call) RunAndReturn(run func(string, string)) *MockSSEBroker_NotifyBucketChange_Call {
	_c.Run(run)
	return _c
}

// NotifyKeyChange provides a mock function with given fields: action, count
func (_m *MockSSEBroker) NotifyKeyChange(action string, count int) {
	_m.Called(action, count)
}

// MockSSEBroker_NotifyKeyChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyKeyChange'
type MockSSEBroker_NotifyKeyChange_Call struct {
	*mock.Call
}

// NotifyKeyChange is a helper method to define mock.On call
//   - action string
//   - count int
func (_e *MockSSEBroker_Expecter) NotifyKeyChange(action interface{}, count interface{}) *MockSSEBroker_NotifyKeyChange_Call {
	return &MockSSEBroker_NotifyKeyChange_Call{Call: _e.mock.On("NotifyKeyChange", action, count)}
}

func (_c *MockSSEBroker_NotifyKeyChange_Call) Run(run func(action string, count int)) *MockSSEBroker_NotifyKeyChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockSSEBroker_NotifyKeyChange_Call) Return() *MockSSEBroker_NotifyKeyChange_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSSEBroker_NotifyKeyChange_Call) RunAndReturn(run func(string, int)) *MockSSEBroker_NotifyKeyChange_Call {
	_c.Run(run)
	return _c
}

// ServeHTTP provides a mock function with given fields: w, r
func (_m *MockSSEBroker) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// MockSSEBroker_ServeHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeHTTP'
type MockSSEBroker_ServeHTTP_Call struct {
	*mock.Call
}

// ServeHTTP is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockSSEBroker_Expecter) ServeHTTP(w interface{}, r interface{}) *MockSSEBroker_ServeHTTP_Call {
	return &MockSSEBroker_ServeHTTP_Call{Call: _e.mock.On("ServeHTTP", w, r)}
}

func (_c *MockSSEBroker_ServeHTTP_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockSSEBroker_ServeHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *MockSSEBroker_ServeHTTP_Call) Return() *MockSSEBroker_ServeHTTP_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSSEBroker_ServeHTTP_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *MockSSEBroker_ServeHTTP_Call {
	_c.Run(run)
	return _c
}

// NewMockSSEBroker creates a new instance of MockSSEBroker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSSEBroker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSSEBroker {
	mock := &MockSSEBroker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
