// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/s3-server/internal/updater"
)

// NewMockUpdaterManager creates a new instance of MockUpdaterManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdaterManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdaterManager {
	mock := &MockUpdaterManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpdaterManager is an autogenerated mock type for the UpdaterManager type
type MockUpdaterManager struct {
	mock.Mock
}

type MockUpdaterManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdaterManager) EXPECT() *MockUpdaterManager_Expecter {
	return &MockUpdaterManager_Expecter{mock: &_m.Mock}
}

// DisableAutoUpdate provides a mock function for the type MockUpdaterManager
func (_mock *MockUpdaterManager) DisableAutoUpdate() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DisableAutoUpdate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUpdaterManager_DisableAutoUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableAutoUpdate'
type MockUpdaterManager_DisableAutoUpdate_Call struct {
	*mock.Call
}

// DisableAutoUpdate is a helper method to define mock.On call
func (_e *MockUpdaterManager_Expecter) DisableAutoUpdate() *MockUpdaterManager_DisableAutoUpdate_Call {
	return &MockUpdaterManager_DisableAutoUpdate_Call{Call: _e.mock.On("DisableAutoUpdate")}
}

func (_c *MockUpdaterManager_DisableAutoUpdate_Call) Run(run func()) *MockUpdaterManager_DisableAutoUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUpdaterManager_DisableAutoUpdate_Call) Return(err error) *MockUpdaterManager_DisableAutoUpdate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUpdaterManager_DisableAutoUpdate_Call) RunAndReturn(run func() error) *MockUpdaterManager_DisableAutoUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// EnableAutoUpdate provides a mock function for the type MockUpdaterManager
func (_mock *MockUpdaterManager) EnableAutoUpdate() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EnableAutoUpdate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUpdaterManager_EnableAutoUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableAutoUpdate'
type MockUpdaterManager_EnableAutoUpdate_Call struct {
	*mock.Call
}

// EnableAutoUpdate is a helper method to define mock.On call
func (_e *MockUpdaterManager_Expecter) EnableAutoUpdate() *MockUpdaterManager_EnableAutoUpdate_Call {
	return &MockUpdaterManager_EnableAutoUpdate_Call{Call: _e.mock.On("EnableAutoUpdate")}
}

func (_c *MockUpdaterManager_EnableAutoUpdate_Call) Run(run func()) *MockUpdaterManager_EnableAutoUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUpdaterManager_EnableAutoUpdate_Call) Return(err error) *MockUpdaterManager_EnableAutoUpdate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUpdaterManager_EnableAutoUpdate_Call) RunAndReturn(run func() error) *MockUpdaterManager_EnableAutoUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// IsAutoUpdateOn provides a mock function for the type MockUpdaterManager
func (_mock *MockUpdaterManager) IsAutoUpdateOn() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsAutoUpdateOn")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockUpdaterManager_IsAutoUpdateOn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAutoUpdateOn'
type MockUpdaterManager_IsAutoUpdateOn_Call struct {
	*mock.Call
}

// IsAutoUpdateOn is a helper method to define mock.On call
func (_e *MockUpdaterManager_Expecter) IsAutoUpdateOn() *MockUpdaterManager_IsAutoUpdateOn_Call {
	return &MockUpdaterManager_IsAutoUpdateOn_Call{Call: _e.mock.On("IsAutoUpdateOn")}
}

func (_c *MockUpdaterManager_IsAutoUpdateOn_Call) Run(run func()) *MockUpdaterManager_IsAutoUpdateOn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUpdaterManager_IsAutoUpdateOn_Call) Return(b bool) *MockUpdaterManager_IsAutoUpdateOn_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockUpdaterManager_IsAutoUpdateOn_Call) RunAndReturn(run func() bool) *MockUpdaterManager_IsAutoUpdateOn_Call {
	_c.Call.Return(run)
	return _c
}

// IsAvailable provides a mock function for the type MockUpdaterManager
func (_mock *MockUpdaterManager) IsAvailable() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsAvailable")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockUpdaterManager_IsAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAvailable'
type MockUpdaterManager_IsAvailable_Call struct {
	*mock.Call
}

// IsAvailable is a helper method to define mock.On call
func (_e *MockUpdaterManager_Expecter) IsAvailable() *MockUpdaterManager_IsAvailable_Call {
	return &MockUpdaterManager_IsAvailable_Call{Call: _e.mock.On("IsAvailable")}
}

func (_c *MockUpdaterManager_IsAvailable_Call) Run(run func()) *MockUpdaterManager_IsAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUpdaterManager_IsAvailable_Call) Return(b bool) *MockUpdaterManager_IsAvailable_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockUpdaterManager_IsAvailable_Call) RunAndReturn(run func() bool) *MockUpdaterManager_IsAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockUpdaterManager
func (_mock *MockUpdaterManager) Status() updater.UpdateStatus {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 updater.UpdateStatus
	if returnFunc, ok := ret.Get(0).(func() updater.UpdateStatus); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(updater.UpdateStatus)
	}
	return r0
}

// MockUpdaterManager_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockUpdaterManager_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *MockUpdaterManager_Expecter) Status() *MockUpdaterManager_Status_Call {
	return &MockUpdaterManager_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *MockUpdaterManager_Status_Call) Run(run func()) *MockUpdaterManager_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUpdaterManager_Status_Call) Return(updateStatus updater.UpdateStatus) *MockUpdaterManager_Status_Call {
	_c.Call.Return(updateStatus)
	return _c
}

func (_c *MockUpdaterManager_Status_Call) RunAndReturn(run func() updater.UpdateStatus) *MockUpdaterManager_Status_Call {
	_c.Call.Return(run)
	return _c
}

// TriggerUpdate provides a mock function for the type MockUpdaterManager
func (_mock *MockUpdaterManager) TriggerUpdate() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TriggerUpdate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUpdaterManager_TriggerUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TriggerUpdate'
type MockUpdaterManager_TriggerUpdate_Call struct {
	*mock.Call
}

// TriggerUpdate is a helper method to define mock.On call
func (_e *MockUpdaterManager_Expecter) TriggerUpdate() *MockUpdaterManager_TriggerUpdate_Call {
	return &MockUpdaterManager_TriggerUpdate_Call{Call: _e.mock.On("TriggerUpdate")}
}

func (_c *MockUpdaterManager_TriggerUpdate_Call) Run(run func()) *MockUpdaterManager_TriggerUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUpdaterManager_TriggerUpdate_Call) Return(err error) *MockUpdaterManager_TriggerUpdate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUpdaterManager_TriggerUpdate_Call) RunAndReturn(run func() error) *MockUpdaterManager_TriggerUpdate_Call {
	_c.Call.Return(run)
	return _c
}
